In [ ]:
file1 = open('/content/drive/MyDrive/Data/test.txt', encoding='utf8')
docA= file1.read()
file2 = open('/content/drive/MyDrive/Data/test1.txt', encoding='utf8')
docB= file2.read()
bowA = docA.split(" ")
bowB = docB.split(" ")

In [ ]:

wordSet = set(bowA).union(set(bowB))
wordDictA = dict.fromkeys(wordSet, 0) 
wordDictB = dict.fromkeys(wordSet, 0) 
for word in bowA:
    wordDictA[word]+=1
    
for word in bowB:
    wordDictB[word]+=1

In [ ]:
for word in bowA:
    wordDictA[word]+=1
    
for word in bowB:
    wordDictB[word]+=1

In [ ]:
wordDictA

{'#world,': 1,
 'Bye.': 1,
 'Good': 0,
 'Hello': 1,
 'I': 1,
 'My': 1,
 'Yaser!.\nWelcome': 1,
 'am': 1,
 'aswin#raghuprasad': 0,
 'is': 1,
 'just': 1,
 'my': 1,
 'name': 1,
 'passing': 1,
 'seeing': 0,
 'through': 1,
 'to': 1,
 'username': 0,
 'world': 1,
 'you.\nMy': 0}

In [ ]:
import pandas as pd
pd.DataFrame([wordDictA, wordDictB])

   to  aswin#raghuprasad  Bye.  username  ...  #world,  passing  my  is
0   1                  0     1         0  ...        1        1   1   1
1   0                  1     0         1  ...        0        0   0   1

[2 rows x 20 columns]

In [ ]:
def computeTF(wordDict, bow):
    tfDict = {}
    bowCount = len(bow)
    for word, count in wordDict.items():
        tfDict[word] = count/float(bowCount)
    return tfDict

In [ ]:
tfBowA = computeTF(wordDictA, bowA)
tfBowB = computeTF(wordDictB, bowB)
tfBowA

{'#world,': 0.06666666666666667,
 'Bye.': 0.06666666666666667,
 'Good': 0.0,
 'Hello': 0.06666666666666667,
 'I': 0.06666666666666667,
 'My': 0.06666666666666667,
 'Yaser!.\nWelcome': 0.06666666666666667,
 'am': 0.06666666666666667,
 'aswin#raghuprasad': 0.0,
 'is': 0.06666666666666667,
 'just': 0.06666666666666667,
 'my': 0.06666666666666667,
 'name': 0.06666666666666667,
 'passing': 0.06666666666666667,
 'seeing': 0.0,
 'through': 0.06666666666666667,
 'to': 0.06666666666666667,
 'username': 0.0,
 'world': 0.06666666666666667,
 'you.\nMy': 0.0}

In [ ]:
tfBowB

{'#world,': 0.0,
 'Bye.': 0.0,
 'Good': 0.16666666666666666,
 'Hello': 0.0,
 'I': 0.0,
 'My': 0.0,
 'Yaser!.\nWelcome': 0.0,
 'am': 0.0,
 'aswin#raghuprasad': 0.16666666666666666,
 'is': 0.16666666666666666,
 'just': 0.0,
 'my': 0.0,
 'name': 0.0,
 'passing': 0.0,
 'seeing': 0.16666666666666666,
 'through': 0.0,
 'to': 0.0,
 'username': 0.16666666666666666,
 'world': 0.0,
 'you.\nMy': 0.16666666666666666}

In [ ]:
def computeIDF(docList):
    import math
    idfDict = {}
    N = len(docList)
    
    idfDict = dict.fromkeys(docList[0].keys(), 0)
    for doc in docList:
        for word, val in doc.items():
            if val > 0:
                idfDict[word] += 1
    
    for word, val in idfDict.items():
        idfDict[word] = math.log10(N / float(val))
        
    return idfDict

In [ ]:
idfs = computeIDF([wordDictA, wordDictB])

In [ ]:
def computeTFIDF(tfBow, idfs):
    tfidf = {}
    for word, val in tfBow.items():
        tfidf[word] = val*idfs[word]
    return tfidf

In [ ]:
tfidfBowA = computeTFIDF(tfBowA, idfs)
tfidfBowB = computeTFIDF(tfBowB, idfs)

In [ ]:
import pandas as pd
pd.DataFrame([tfidfBowA, tfidfBowB])

      world   through      name  ...  aswin#raghuprasad   passing        am
0  0.020069  0.020069  0.020069  ...           0.000000  0.020069  0.020069
1  0.000000  0.000000  0.000000  ...           0.050172  0.000000  0.000000

[2 rows x 20 columns]

In [ ]:
print(alldocs)

{'Data\\test.txt': 'hello world my name is aswin welcome to my world i am just passing through bye', 'Data\\test1.txt': 'good seeing you my username is aswin raghuprasad'}

In [ ]:
tf_idf

{'Data\\test.txt': {'i': 0.043321699,
  'hello': 0.043321699,
  'am': 0.043321699,
  'passing': 0.043321699,
  'aswin': 0.0,
  'welcome': 0.043321699,
  'to': 0.043321699,
  'just': 0.043321699,
  'my': 0.0,
  'name': 0.043321699,
  'bye': 0.043321699,
  'is': 0.0,
  'world': 0.086643398,
  'through': 0.043321699},
 'Data\\test1.txt': {'seeing': 0.086643398,
  'aswin': 0.0,
  'good': 0.086643398,
  'my': 0.0,
  'is': 0.0,
  'raghuprasad': 0.086643398,
  'you': 0.086643398,
  'username': 0.086643398}}

In [ ]:
s = "my name is username"
tokens = s.split()
keys = tf_idf.keys()
document_scores = { key:0 for key in keys}
for key in keys:
    for word in tf_idf[key]:
        if word in tokens:
            document_scores[key] += tf_idf[key][word]
print(document_scores)

{'Data\\test.txt': 0.043321699, 'Data\\test1.txt': 0.086643398}

In [ ]:
tokens

['my', 'name', 'is', 'username']

**تغییرات داده شده**

In [ ]:
# this will open the file
file = open('/content/drive/MyDrive/Data/test.txt', encoding='utf8')
read = file.read()
file.seek(0)
read

# to obtain the
# number of lines
# in file
line = 1
for word in read:
	if word == '\n':
		line += 1
print("Number of lines in file is: ", line)

# create a list to
# store each line as
# an element of list
array = []
for i in range(line):
	array.append(file.readline())

array

Number of lines in file is:  2

['Hello world My name is Yaser!.\n',
 'Welcome to my #world, I am just passing through Bye.']

***حذف علائم***

In [ ]:
punc = '''!()-[]{};:'"\, <>./?@#$%^&*_~'''
for ele in read:
	if ele in punc:
		read = read.replace(ele, " ")
		
read

# to maintain uniformity
read=read.lower()					
read

'hello world my name is yaser  \nwelcome to my  world  i am just passing through bye '

***حذف کلمات اضافه***

In [ ]:
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')

for i in range(1):
	# this will convert
	# the word into tokens
	text_tokens = word_tokenize(read)

tokens_without_sw = [
	word for word in text_tokens if not word in stopwords.words()]

print(tokens_without_sw)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
['hello', 'world', 'yaser', 'welcome', 'world', 'passing', 'bye']

*** inverted index ایجاد ***

In [ ]:
dict = {}

for i in range(line):
	check = array[i].lower()
	for item in tokens_without_sw:

		if item in check:
			if item not in dict:
				dict[item] = []

			if item in dict:
				dict[item].append(i+1)

dict

{'bye': [2],
 'hello': [1],
 'passing': [2],
 'welcome': [2],
 'world': [1, 1, 2, 2],
 'yaser': [1]}

**query boolean**

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
from nltk.tokenize import sent_tokenize , word_tokenize
import glob
import re
import os
import numpy as np
import sys
nltk.download('stopwords')
Stopwords = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
def finding_all_unique_words_and_freq(words):
    words_unique = []
    word_freq = {}
    for word in words:
        if word not in words_unique:
            words_unique.append(word)
    for word in words_unique:
        word_freq[word] = words.count(word)
    return word_freq
def finding_freq_of_word_in_doc(word,words):
    freq = words.count(word)
        
def remove_special_characters(text):
    regex = re.compile('[^a-zA-Z0-9\s]')
    text_returned = re.sub(regex,'',text)
    return text_returned

In [ ]:
all_words = []
dict_global = {}
file_folder = '/content/drive/MyDrive/Data/*'
idx = 1
files_with_index = {}
for file in glob.glob(file_folder):
    print(file)
    fname = file
    file = open(file , "r")
    text = file.read()
    #print (text)
    text = remove_special_characters(text)
    text = re.sub(re.compile('\d'),'',text)
    sentences = sent_tokenize(text)
    words = word_tokenize(text)
    words = [word for word in words if len(words)>1]
    words = [word.lower() for word in words]
    words = [word for word in words if word not in Stopwords]
    dict_global.update(finding_all_unique_words_and_freq(words))
    files_with_index[idx] = os.path.basename(fname)
    idx = idx + 1
    
unique_words_all = set(dict_global.keys())

/content/drive/MyDrive/Data/test1.txt
/content/drive/MyDrive/Data/test.txt

In [ ]:
class Node:
    def __init__(self ,docId, freq = None):
        self.freq = freq
        self.doc = docId
        self.nextval = None
    
class SlinkedList:
    def __init__(self ,head = None):
        self.head = head

In [ ]:
linked_list_data = {}
for word in unique_words_all:
    linked_list_data[word] = SlinkedList()
    linked_list_data[word].head = Node(1,Node)
word_freq_in_doc = {}
idx = 1
for file in glob.glob(file_folder):
    file = open(file, "r")
    text = file.read()
    text = remove_special_characters(text)
    text = re.sub(re.compile('\d'),'',text)
    sentences = sent_tokenize(text)
    words = word_tokenize(text)
    words = [word for word in words if len(words)>1]
    words = [word.lower() for word in words]
    words = [word for word in words if word not in Stopwords]
    word_freq_in_doc = finding_all_unique_words_and_freq(words)
    for word in word_freq_in_doc.keys():
        linked_list = linked_list_data[word].head
        while linked_list.nextval is not None:
            linked_list = linked_list.nextval
        linked_list.nextval = Node(idx ,word_freq_in_doc[word])
    idx = idx + 1

In [ ]:
query = input('Enter your query:')
query = word_tokenize(query)
connecting_words = []
cnt = 1
different_words = []
for word in query:
    if word.lower() != "and" and word.lower() != "or" and word.lower() != "not":
        different_words.append(word.lower())
    else:
        connecting_words.append(word.lower())
print(connecting_words)
total_files = len(files_with_index)
zeroes_and_ones = []
zeroes_and_ones_of_all_words = []
for word in (different_words):
    if word.lower() in unique_words_all:
        zeroes_and_ones = [0] * total_files
        linkedlist = linked_list_data[word].head
        print(word)
        while linkedlist.nextval is not None:
            zeroes_and_ones[linkedlist.nextval.doc - 1] = 1
            linkedlist = linkedlist.nextval
        zeroes_and_ones_of_all_words.append(zeroes_and_ones)
    else:
        print(word," not found")
        sys.exit()
print(zeroes_and_ones_of_all_words)
for word in connecting_words:
    word_list1 = zeroes_and_ones_of_all_words[0]
    word_list2 = zeroes_and_ones_of_all_words[1]
    if word == "and":
        bitwise_op = [w1 & w2 for (w1,w2) in zip(word_list1,word_list2)]
        zeroes_and_ones_of_all_words.remove(word_list1)
        zeroes_and_ones_of_all_words.remove(word_list2)
        zeroes_and_ones_of_all_words.insert(0, bitwise_op);
    elif word == "or":
        bitwise_op = [w1 | w2 for (w1,w2) in zip(word_list1,word_list2)]
        zeroes_and_ones_of_all_words.remove(word_list1)
        zeroes_and_ones_of_all_words.remove(word_list2)
        zeroes_and_ones_of_all_words.insert(0, bitwise_op);
    elif word == "not":
        bitwise_op = [not w1 for w1 in word_list2]
        bitwise_op = [int(b == True) for b in bitwise_op]
        zeroes_and_ones_of_all_words.remove(word_list2)
        zeroes_and_ones_of_all_words.remove(word_list1)
        bitwise_op = [w1 & w2 for (w1,w2) in zip(word_list1,bitwise_op)]
        zeroes_and_ones_of_all_words.insert(0, bitwise_op);
        
files = []    
print(zeroes_and_ones_of_all_words)
lis = zeroes_and_ones_of_all_words[0]
cnt = 1
for index in lis:
    if index == 1:
        files.append(files_with_index[cnt])
    cnt = cnt+1
    
print(files)

Enter your query:Welcome
[]
welcome
[[0, 1]]
[[0, 1]]
['test.txt']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
from scipy import spatial
List1 = [4, 47, 8, 3]
List2 = [3, 52, 12, 16]
result = 1 - spatial.distance.cosine(List1, List2)
print(result)

0.9720951480078084